import { defineConfig } from 'tsdown';

export default defineConfig({
    failOnWarn: false,
    entry: [
        'src/index.ts',
        'src/stdio.ts',
        'src/types.ts',
        'src/inMemory.ts',
        'src/experimental/tasks.ts',
        'src/server/index.ts',
        'src/server/mcp.ts',
        'src/server/zod-compat.ts',
        'src/server/completable.ts',
        'src/server/sse.ts',
        'src/server/stdio.ts',
        'src/server/streamableHttp.ts',
        'src/server/auth/types.ts',
        'src/server/auth/errors.ts',
        'src/server/auth/middleware/bearerAuth.ts',
        'src/server/auth/router.ts',
        'src/server/auth/provider.ts',
        'src/server/auth/clients.ts',
        'src/client/index.ts',
        'src/client/stdio.ts',
        'src/client/streamableHttp.ts',
        'src/client/sse.ts',
        'src/client/auth.ts',
        'src/shared/protocol.ts',
        'src/shared/transport.ts',
        'src/shared/auth.ts',
        'src/shared/stdio.ts',
        'src/server/webStandardStreamableHttp.ts',
        'src/validation/types.ts',
        'src/validation/cfworker-provider.ts',
        'src/validation/ajv-provider.ts'
    ],
    format: ['esm'],
    outDir: 'dist',
    clean: true,
    sourcemap: true,
    target: 'esnext',
    platform: 'node',
    dts: false,
    external: [/^@modelcontextprotocol\//]
});
