name: 'Generate Multi-Version Docs'
description: 'Generates combined V1 + V2 TypeDoc API documentation'

inputs:
    output-dir:
        description: 'Directory to write combined docs to'
        required: false
        default: 'tmp/docs-combined'

runs:
    using: composite
    steps:
        - name: Generate multi-version docs
          shell: bash
          run: bash scripts/generate-multidoc.sh ${{ inputs.output-dir }}
