/**
 * Curated public API exports from @modelcontextprotocol/core.
 *
 * This file is re-exported by both @modelcontextprotocol/client and
 * @modelcontextprotocol/server so that users can import any public symbol
 * from either package. Internal utilities (Zod compat, stdio parsing,
 * Protocol base class, etc.) are intentionally excluded.
 *
 * When adding new public symbols to core, add them here once — both
 * client and server will pick them up automatically.
 */

// --- auth/errors.ts ---
export {
    AccessDeniedError,
    CustomOAuthError,
    InsufficientScopeError,
    InvalidClientError,
    InvalidClientMetadataError,
    InvalidGrantError,
    InvalidRequestError,
    InvalidScopeError,
    InvalidTargetError,
    InvalidTokenError,
    MethodNotAllowedError,
    OAuthError,
    ServerError,
    TemporarilyUnavailableError,
    TooManyRequestsError,
    UnauthorizedClientError,
    UnsupportedGrantTypeError,
    UnsupportedResponseTypeError,
    UnsupportedTokenTypeError
} from './auth/errors.js';

// --- shared/auth.ts ---
export type {
    AuthorizationServerMetadata,
    OAuthClientInformation,
    OAuthClientInformationFull,
    OAuthClientInformationMixed,
    OAuthClientMetadata,
    OAuthClientRegistrationError,
    OAuthErrorResponse,
    OAuthMetadata,
    OAuthProtectedResourceMetadata,
    OAuthTokenRevocationRequest,
    OAuthTokens,
    OpenIdProviderDiscoveryMetadata,
    OpenIdProviderMetadata
} from './shared/auth.js';
export {
    OAuthClientInformationFullSchema,
    OAuthClientInformationSchema,
    OAuthClientMetadataSchema,
    OAuthClientRegistrationErrorSchema,
    OAuthErrorResponseSchema,
    OAuthMetadataSchema,
    OAuthProtectedResourceMetadataSchema,
    OAuthTokenRevocationRequestSchema,
    OAuthTokensSchema,
    OpenIdProviderDiscoveryMetadataSchema,
    OpenIdProviderMetadataSchema
} from './shared/auth.js';

// --- shared/authUtils.ts ---
export { checkResourceAllowed, resourceUrlFromServerUrl } from './shared/authUtils.js';

// --- shared/metadataUtils.ts ---
export { getDisplayName } from './shared/metadataUtils.js';

// --- shared/protocol.ts (excluding Protocol class, mergeCapabilities) ---
export type {
    NotificationOptions,
    ProgressCallback,
    ProtocolOptions,
    RequestHandlerExtra,
    RequestOptions,
    RequestTaskStore,
    TaskRequestOptions
} from './shared/protocol.js';
export { DEFAULT_REQUEST_TIMEOUT_MSEC } from './shared/protocol.js';

// --- shared/responseMessage.ts (excluding AsyncGeneratorValue) ---
export type {
    BaseResponseMessage,
    ErrorMessage,
    ResponseMessage,
    ResultMessage,
    TaskCreatedMessage,
    TaskStatusMessage
} from './shared/responseMessage.js';
export { takeResult, toArrayAsync } from './shared/responseMessage.js';

// --- shared/transport.ts (excluding normalizeHeaders) ---
export type { FetchLike, Transport, TransportSendOptions } from './shared/transport.js';
export { createFetchWithInit } from './shared/transport.js';

// --- shared/uriTemplate.ts ---
export type { Variables } from './shared/uriTemplate.js';
export { UriTemplate } from './shared/uriTemplate.js';

// --- types/types.ts ---
export type {
    Annotations,
    AudioContent,
    AuthInfo,
    BaseMetadata,
    BlobResourceContents,
    BooleanSchema,
    CallToolRequest,
    CallToolRequestParams,
    CallToolResult,
    CancelledNotification,
    CancelledNotificationParams,
    CancelTaskRequest,
    CancelTaskResult,
    ClientCapabilities,
    ClientNotification,
    ClientRequest,
    ClientResult,
    CompatibilityCallToolResult,
    CompleteRequest,
    CompleteRequestParams,
    CompleteRequestPrompt,
    CompleteRequestResourceTemplate,
    CompleteResult,
    ContentBlock,
    CreateMessageRequest,
    CreateMessageRequestParams,
    CreateMessageRequestParamsBase,
    CreateMessageRequestParamsWithTools,
    CreateMessageResult,
    CreateMessageResultWithTools,
    CreateTaskResult,
    Cursor,
    ElicitationCompleteNotification,
    ElicitationCompleteNotificationParams,
    ElicitRequest,
    ElicitRequestFormParams,
    ElicitRequestParams,
    ElicitRequestURLParams,
    ElicitResult,
    EmbeddedResource,
    EmptyResult,
    EnumSchema,
    GetPromptRequest,
    GetPromptRequestParams,
    GetPromptResult,
    GetTaskPayloadRequest,
    GetTaskPayloadResult,
    GetTaskRequest,
    GetTaskResult,
    Icon,
    Icons,
    ImageContent,
    Implementation,
    InitializedNotification,
    InitializeRequest,
    InitializeRequestParams,
    InitializeResult,
    JSONRPCErrorResponse,
    JSONRPCMessage,
    JSONRPCNotification,
    JSONRPCRequest,
    JSONRPCResponse,
    JSONRPCResultResponse,
    LegacyTitledEnumSchema,
    ListChangedCallback,
    ListChangedHandlers,
    ListChangedOptions,
    ListPromptsRequest,
    ListPromptsResult,
    ListResourcesRequest,
    ListResourcesResult,
    ListResourceTemplatesRequest,
    ListResourceTemplatesResult,
    ListRootsRequest,
    ListRootsResult,
    ListTasksRequest,
    ListTasksResult,
    ListToolsRequest,
    ListToolsResult,
    LoggingLevel,
    LoggingMessageNotification,
    LoggingMessageNotificationParams,
    MessageExtraInfo,
    ModelHint,
    ModelPreferences,
    MultiSelectEnumSchema,
    Notification,
    NotificationParams,
    NumberSchema,
    PaginatedRequest,
    PaginatedRequestParams,
    PaginatedResult,
    PingRequest,
    PrimitiveSchemaDefinition,
    Progress,
    ProgressNotification,
    ProgressNotificationParams,
    ProgressToken,
    Prompt,
    PromptArgument,
    PromptListChangedNotification,
    PromptMessage,
    PromptReference,
    ReadResourceRequest,
    ReadResourceRequestParams,
    ReadResourceResult,
    RelatedTaskMetadata,
    Request,
    RequestId,
    RequestInfo,
    RequestMeta,
    RequestParams,
    Resource,
    ResourceContents,
    ResourceLink,
    ResourceListChangedNotification,
    ResourceRequestParams,
    ResourceTemplateReference,
    ResourceTemplateType,
    ResourceUpdatedNotification,
    ResourceUpdatedNotificationParams,
    Result,
    Role,
    Root,
    RootsListChangedNotification,
    SamplingContent,
    SamplingMessage,
    SamplingMessageContentBlock,
    ServerCapabilities,
    ServerNotification,
    ServerRequest,
    ServerResult,
    SetLevelRequest,
    SetLevelRequestParams,
    SingleSelectEnumSchema,
    StringSchema,
    SubscribeRequest,
    SubscribeRequestParams,
    Task,
    TaskAugmentedRequestParams,
    TaskCreationParams,
    TaskMetadata,
    TaskStatus,
    TaskStatusNotification,
    TaskStatusNotificationParams,
    TextContent,
    TextResourceContents,
    TitledMultiSelectEnumSchema,
    TitledSingleSelectEnumSchema,
    Tool,
    ToolAnnotations,
    ToolChoice,
    ToolExecution,
    ToolListChangedNotification,
    ToolResultContent,
    ToolUseContent,
    UnsubscribeRequest,
    UnsubscribeRequestParams,
    UntitledMultiSelectEnumSchema,
    UntitledSingleSelectEnumSchema
} from './types/types.js';
export {
    AnnotationsSchema,
    assertCompleteRequestPrompt,
    assertCompleteRequestResourceTemplate,
    AudioContentSchema,
    BaseMetadataSchema,
    BlobResourceContentsSchema,
    BooleanSchemaSchema,
    CallToolRequestParamsSchema,
    CallToolRequestSchema,
    CallToolResultSchema,
    CancelledNotificationParamsSchema,
    CancelledNotificationSchema,
    CancelTaskRequestSchema,
    CancelTaskResultSchema,
    ClientCapabilitiesSchema,
    ClientNotificationSchema,
    ClientRequestSchema,
    ClientResultSchema,
    ClientTasksCapabilitySchema,
    CompatibilityCallToolResultSchema,
    CompleteRequestParamsSchema,
    CompleteRequestSchema,
    CompleteResultSchema,
    ContentBlockSchema,
    CreateMessageRequestParamsSchema,
    CreateMessageRequestSchema,
    CreateMessageResultSchema,
    CreateMessageResultWithToolsSchema,
    CreateTaskResultSchema,
    CursorSchema,
    DEFAULT_NEGOTIATED_PROTOCOL_VERSION,
    ElicitationCompleteNotificationParamsSchema,
    ElicitationCompleteNotificationSchema,
    ElicitRequestFormParamsSchema,
    ElicitRequestParamsSchema,
    ElicitRequestSchema,
    ElicitRequestURLParamsSchema,
    ElicitResultSchema,
    EmbeddedResourceSchema,
    EmptyResultSchema,
    EnumSchemaSchema,
    ErrorCode,
    GetPromptRequestParamsSchema,
    GetPromptRequestSchema,
    GetPromptResultSchema,
    GetTaskPayloadRequestSchema,
    GetTaskPayloadResultSchema,
    GetTaskRequestSchema,
    GetTaskResultSchema,
    IconSchema,
    IconsSchema,
    ImageContentSchema,
    ImplementationSchema,
    InitializedNotificationSchema,
    InitializeRequestParamsSchema,
    InitializeRequestSchema,
    InitializeResultSchema,
    isInitializedNotification,
    isInitializeRequest,
    isJSONRPCErrorResponse,
    isJSONRPCNotification,
    isJSONRPCRequest,
    isJSONRPCResultResponse,
    isTaskAugmentedRequestParams,
    JSONRPC_VERSION,
    JSONRPCErrorResponseSchema,
    JSONRPCMessageSchema,
    JSONRPCNotificationSchema,
    JSONRPCRequestSchema,
    JSONRPCResponseSchema,
    JSONRPCResultResponseSchema,
    LATEST_PROTOCOL_VERSION,
    LegacyTitledEnumSchemaSchema,
    ListChangedOptionsBaseSchema,
    ListPromptsRequestSchema,
    ListPromptsResultSchema,
    ListResourcesRequestSchema,
    ListResourcesResultSchema,
    ListResourceTemplatesRequestSchema,
    ListResourceTemplatesResultSchema,
    ListRootsRequestSchema,
    ListRootsResultSchema,
    ListTasksRequestSchema,
    ListTasksResultSchema,
    ListToolsRequestSchema,
    ListToolsResultSchema,
    LoggingLevelSchema,
    LoggingMessageNotificationParamsSchema,
    LoggingMessageNotificationSchema,
    McpError,
    ModelHintSchema,
    ModelPreferencesSchema,
    MultiSelectEnumSchemaSchema,
    NotificationSchema,
    NumberSchemaSchema,
    PaginatedRequestParamsSchema,
    PaginatedRequestSchema,
    PaginatedResultSchema,
    PingRequestSchema,
    PrimitiveSchemaDefinitionSchema,
    ProgressNotificationParamsSchema,
    ProgressNotificationSchema,
    ProgressSchema,
    ProgressTokenSchema,
    PromptArgumentSchema,
    PromptListChangedNotificationSchema,
    PromptMessageSchema,
    PromptReferenceSchema,
    PromptSchema,
    ReadResourceRequestParamsSchema,
    ReadResourceRequestSchema,
    ReadResourceResultSchema,
    RELATED_TASK_META_KEY,
    RelatedTaskMetadataSchema,
    RequestIdSchema,
    RequestSchema,
    ResourceContentsSchema,
    ResourceLinkSchema,
    ResourceListChangedNotificationSchema,
    ResourceRequestParamsSchema,
    ResourceSchema,
    ResourceTemplateReferenceSchema,
    ResourceTemplateSchema,
    ResourceUpdatedNotificationParamsSchema,
    ResourceUpdatedNotificationSchema,
    ResultSchema,
    RoleSchema,
    RootSchema,
    RootsListChangedNotificationSchema,
    SamplingContentSchema,
    SamplingMessageContentBlockSchema,
    SamplingMessageSchema,
    ServerCapabilitiesSchema,
    ServerNotificationSchema,
    ServerRequestSchema,
    ServerResultSchema,
    ServerTasksCapabilitySchema,
    SetLevelRequestParamsSchema,
    SetLevelRequestSchema,
    SingleSelectEnumSchemaSchema,
    StringSchemaSchema,
    SubscribeRequestParamsSchema,
    SubscribeRequestSchema,
    SUPPORTED_PROTOCOL_VERSIONS,
    TaskAugmentedRequestParamsSchema,
    TaskCreationParamsSchema,
    TaskMetadataSchema,
    TaskSchema,
    TaskStatusNotificationParamsSchema,
    TaskStatusNotificationSchema,
    TaskStatusSchema,
    TextContentSchema,
    TextResourceContentsSchema,
    TitledMultiSelectEnumSchemaSchema,
    TitledSingleSelectEnumSchemaSchema,
    ToolAnnotationsSchema,
    ToolChoiceSchema,
    ToolExecutionSchema,
    ToolListChangedNotificationSchema,
    ToolResultContentSchema,
    ToolSchema,
    ToolUseContentSchema,
    UnsubscribeRequestParamsSchema,
    UnsubscribeRequestSchema,
    UntitledMultiSelectEnumSchemaSchema,
    UntitledSingleSelectEnumSchemaSchema,
    UrlElicitationRequiredError
} from './types/types.js';

// --- util/inMemory.ts ---
export { InMemoryTransport } from './util/inMemory.js';

// --- experimental/tasks (from core) ---
export type {
    BaseQueuedMessage,
    CreateTaskOptions,
    CreateTaskRequestHandlerExtra,
    QueuedError,
    QueuedMessage,
    QueuedNotification,
    QueuedRequest,
    QueuedResponse,
    TaskMessageQueue,
    TaskRequestHandlerExtra,
    TaskStore,
    TaskToolExecution
} from './experimental/index.js';
export {
    assertClientRequestTaskCapability,
    assertToolsCallTaskCapability,
    InMemoryTaskMessageQueue,
    InMemoryTaskStore,
    isTerminal
} from './experimental/index.js';

// --- validation/types.ts ---
export type { JsonSchemaType, JsonSchemaValidator, jsonSchemaValidator, JsonSchemaValidatorResult } from './validation/types.js';

// --- validation providers ---
export type { CfWorkerSchemaDraft } from './validation/cfWorkerProvider.js';
export { AjvJsonSchemaValidator } from './validation/ajvProvider.js';
export { CfWorkerJsonSchemaValidator } from './validation/cfWorkerProvider.js';
