import { existsSync, readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { defineConfig, type DefaultTheme } from 'vitepress';

import { generateLlmsArtifacts } from './llms';
import { guideSidebar } from './nav';
import { githubSlug, rewriteSkillLink } from './skill';

const docsDir = resolve(dirname(fileURLToPath(import.meta.url)), '..');

/** Absolute site URL (origin + base), the single copy every consumer derives from. */
const siteUrl = 'https://ts.sdk.modelcontextprotocol.io/v2';

/**
 * The API Reference sidebar is generated by `pnpm docs:api` (typedoc + typedoc-vitepress-theme)
 * into docs/api/typedoc-sidebar.json. When it is missing (e.g. `docs:dev` before `docs:api`),
 * fall back to an empty group with a hint instead of crashing.
 */
function apiSidebarItems(): DefaultTheme.SidebarItem[] {
    const sidebarPath = resolve(docsDir, 'api/typedoc-sidebar.json');
    if (!existsSync(sidebarPath)) {
        console.warn(`[docs] ${sidebarPath} not found — run \`pnpm docs:api\` first to populate the API Reference section.`);
        return [];
    }
    return JSON.parse(readFileSync(sidebarPath, 'utf8'));
}

export default defineConfig({
    title: 'MCP TypeScript SDK',
    description: 'The TypeScript SDK implementation of the Model Context Protocol specification.',
    base: '/v2/',
    // VitePress does not base-prefix head hrefs, so /v2/ is spelled out here.
    head: [['link', { rel: 'icon', type: 'image/svg+xml', href: '/v2/favicon.svg' }]],
    srcExclude: ['v1/**', '_meta/**', 'behavior-surface-pins.md'],
    sitemap: { hostname: `${siteUrl}/` },
    markdown: {
        config(md) {
            // Spec-generated JSDoc (packages/core-internal/src/types/spec.types.*.ts) carries
            // site-root-relative links like /specification/draft/basic/index#meta that are meant
            // to resolve on modelcontextprotocol.io. Rewrite them at render time so they work on
            // this site (and so the dead-link check sees them as external).
            const orig = md.renderer.rules.link_open ?? ((tokens, idx, options, _env, self) => self.renderToken(tokens, idx, options));
            md.renderer.rules.link_open = (tokens, idx, options, env, self) => {
                const href = tokens[idx].attrGet('href');
                if (href?.startsWith('/specification/')) {
                    tokens[idx].attrSet('href', `https://modelcontextprotocol.io${href}`);
                }
                return orig(tokens, idx, options, env, self);
            };
            // Resolve skill links on the assembled page, then GitHub-style anchors to VitePress's heading ids.
            md.core.ruler.push('page_links', state => {
                const ids = new Set<string>();
                const byGithubSlug = new Map<string, string>();
                const seen = new Map<string, number>();
                state.tokens.forEach((token, i) => {
                    const id = token.type === 'heading_open' ? token.attrGet('id') : null;
                    if (!id) return;
                    const slug = githubSlug(state.tokens[i + 1]!.content);
                    const n = seen.get(slug) ?? 0;
                    seen.set(slug, n + 1);
                    ids.add(id);
                    byGithubSlug.set(n ? `${slug}-${n}` : slug, id);
                });
                for (const link of state.tokens.flatMap(token => token.children ?? [])) {
                    const href = link.type === 'link_open' ? link.attrGet('href') : null;
                    if (!href) continue;
                    const rewritten = rewriteSkillLink(href, state.env.relativePath, siteUrl);
                    const anchor = /^#(.+)$/.exec(rewritten)?.[1];
                    const id = anchor && !ids.has(anchor) ? byGithubSlug.get(decodeURIComponent(anchor)) : undefined;
                    link.attrSet('href', id ? `#${id}` : rewritten);
                }
            });
        }
    },
    buildEnd(siteConfig) {
        generateLlmsArtifacts(docsDir, siteConfig.outDir, siteUrl);
    },
    transformPageData(pageData) {
        // Every guide page has a markdown rendition next to its HTML (llms.ts);
        // advertise it to tools via a rel=alternate link. The API reference has none.
        if (!pageData.relativePath.startsWith('api/')) {
            pageData.frontmatter.head ??= [];
            pageData.frontmatter.head.push([
                'link',
                { rel: 'alternate', type: 'text/markdown', href: `${siteUrl}/${pageData.relativePath}` }
            ]);
        }
    },
    themeConfig: {
        nav: [
            { text: 'Get started', link: '/get-started/first-server', activeMatch: '^/get-started/' },
            { text: 'Servers', link: '/servers/tools', activeMatch: '^/(servers|serving)/' },
            { text: 'Clients', link: '/clients/connect', activeMatch: '^/clients/' },
            { text: 'Migration', link: '/migration/', activeMatch: '^/migration/' },
            { text: 'API Reference', link: '/api/', activeMatch: '^/api/' },
            { text: 'V1 Docs', link: 'https://ts.sdk.modelcontextprotocol.io/' }
        ],
        sidebar: [
            ...guideSidebar,
            {
                text: 'API Reference',
                collapsed: true,
                items: apiSidebarItems()
            }
        ],
        outline: { level: [2, 3] },
        search: { provider: 'local' },
        socialLinks: [{ icon: 'github', link: 'https://github.com/modelcontextprotocol/typescript-sdk' }]
    }
});
