#!/usr/bin/env node
import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

// Read the original types.ts file
const typesPath = join(__dirname, '../src/types.ts');
const strictTypesPath = join(__dirname, '../src/strictTypes.ts');

let content = readFileSync(typesPath, 'utf-8');

// Add header comment
const header = `/**
 * Types remove unknown
 * properties to maintaining compatibility with protocol extensions.
 * 
 * - Protocol compatoble: Unknown fields from extended implementations are removed, not rejected
 * - Forward compatibility: Works with servers/clients that have additional fields
 * 
 * @generated by scripts/generateStrictTypes.ts
 */

`;

// Replace all .passthrough() with .strip()
content = content.replace(/\.passthrough\(\)/g, '.strip()');

// Special handling for experimental and capabilities that should remain open
// These are explicitly designed to be extensible
const patternsToKeepOpen = [
  // Keep experimental fields open as they're meant for extensions
  /experimental: z\.optional\(z\.object\(\{\}\)\.strip\(\)\)/g,
  // Keep _meta fields open as they're meant for arbitrary metadata
  /_meta: z\.optional\(z\.object\(\{\}\)\.strip\(\)\)/g,
  // Keep JSON Schema properties open as they can have arbitrary fields
  /properties: z\.optional\(z\.object\(\{\}\)\.strip\(\)\)/g,
  // Keep BaseRequestParamsSchema passthrough for JSON-RPC param compatibility
  /const BaseRequestParamsSchema = z\s*\n\s*\.object\([\s\S]*?\)\s*\n\s*\.strip\(\)/g,
  // Keep BaseNotificationParamsSchema passthrough for JSON-RPC param compatibility  
  /const BaseNotificationParamsSchema = z\s*\n\s*\.object\([\s\S]*?\)\s*\n\s*\.strip\(\)/g,
  // Keep RequestMetaSchema passthrough for extensibility
  /const RequestMetaSchema = z\s*\n\s*\.object\([\s\S]*?\)\s*\n\s*\.strip\(\)/g,
  // Keep structuredContent passthrough for tool-specific output
  /structuredContent: z\.object\(\{\}\)\.strip\(\)\.optional\(\)/g,
  // Keep metadata passthrough for provider-specific data in sampling
  /metadata: z\.optional\(z\.object\(\{\}\)\.strip\(\)\)/g,
];

// Revert strip back to passthrough for these special cases
patternsToKeepOpen.forEach(pattern => {
  content = content.replace(pattern, (match) =>
    match.replace('.strip()', '.passthrough()')
  );
});

// Add a comment explaining the difference
const explanation = `
/**
 * Note: The following remain open (using .passthrough()):
 * - experimental: Designed for protocol extensions
 * - _meta: Designed for arbitrary metadata
 * - properties: JSON Schema properties that can have arbitrary fields
 * - BaseRequestParamsSchema: Required for JSON-RPC param compatibility
 * - BaseNotificationParamsSchema: Required for JSON-RPC param compatibility
 * - RequestMetaSchema: Required for protocol extensibility
 * - structuredContent: Tool-specific output that can have arbitrary fields
 * - metadata: Provider-specific metadata in sampling requests
 * 
 * All other objects use .strip() to remove unknown properties while
 * maintaining compatibility with extended protocols.
 */
`;

// Insert the explanation after the imports
const importEndIndex = content.lastIndexOf('import');
const importEndLineIndex = content.indexOf('\n', importEndIndex);
content = content.slice(0, importEndLineIndex + 1) + explanation + content.slice(importEndLineIndex + 1);

// Write the strict types file
writeFileSync(strictTypesPath, header + content);

console.log('Generated strictTypes.ts successfully!');
