/**
 * Post-processes the generated schemas from ts-to-zod for Zod v4 compatibility.
 *
 * ts-to-zod generates code that has compatibility issues with Zod v4:
 * 1. Uses z.record().and(z.object()) for index signatures which doesn't support .extend()
 * 2. Uses "zod" import instead of "zod/v4"
 *
 * This script fixes these issues.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const PROJECT_ROOT = join(__dirname, '..');

const SCHEMA_FILE = join(PROJECT_ROOT, 'src', 'schemas.generated.ts');

function main() {
    console.log('Post-processing generated schemas for Zod v4 compatibility...');

    let content = readFileSync(SCHEMA_FILE, 'utf-8');

    // 1. Update import to use zod/v4
    content = content.replace(
        'import { z } from "zod";',
        'import { z } from "zod/v4";'
    );

    // 2. Add post-processing comment
    content = content.replace(
        '// Generated by ts-to-zod',
        '// Generated by ts-to-zod\n// Post-processed for Zod v4 compatibility (run: npm run generate:schemas)'
    );

    // 3. Replace resultSchema's z.record().and(z.object()) pattern with z.looseObject()
    // This pattern doesn't support .extend() which is needed for derived schemas
    content = content.replace(
        /export const resultSchema = z\.record\(z\.string\(\), z\.unknown\(\)\)\.and\(z\.object\(\{\s*_meta: z\.record\(z\.string\(\), z\.unknown\(\)\)\.optional\(\)\s*\}\)\);/,
        `// Changed from z.record().and(z.object()) to z.looseObject() to support .extend()
export const resultSchema = z.looseObject({
    _meta: z.record(z.string(), z.unknown()).optional()
});`
    );

    writeFileSync(SCHEMA_FILE, content, 'utf-8');
    console.log('Post-processing complete!');
}

main();
