// Generated by ts-to-zod
// Post-processed for Zod v4 compatibility (run: npm run generate:schemas)
import { z } from "zod/v4";

export const progressTokenSchema = z.union([z.string(), z.number()]);

export const cursorSchema = z.string();

export const requestParamsSchema = z.object({
    _meta: z.record(z.string(), z.unknown()).and(z.object({
        progressToken: progressTokenSchema.optional()
    })).optional()
});

export const requestSchema = z.object({
    method: z.string(),
    params: z.record(z.string(), z.any()).optional()
});

export const notificationParamsSchema = z.object({
    _meta: z.record(z.string(), z.unknown()).optional()
});

export const notificationSchema = z.object({
    method: z.string(),
    params: z.record(z.string(), z.any()).optional()
});

// Changed from z.record().and(z.object()) to z.looseObject() to support .extend()
export const resultSchema = z.looseObject({
    _meta: z.record(z.string(), z.unknown()).optional()
});

export const errorSchema = z.object({
    code: z.number(),
    message: z.string(),
    data: z.unknown().optional()
});

export const requestIdSchema = z.union([z.string(), z.number()]);

export const jsonrpcRequestSchema = requestSchema.extend({
    jsonrpc: z.any(),
    id: requestIdSchema
});

export const jsonrpcNotificationSchema = notificationSchema.extend({
    jsonrpc: z.any()
});

export const jsonrpcResponseSchema = z.object({
    jsonrpc: z.any(),
    id: requestIdSchema,
    result: resultSchema
});

export const jsonrpcErrorSchema = z.object({
    jsonrpc: z.any(),
    id: requestIdSchema,
    error: errorSchema
});

export const elicitRequestUrlParamsSchema = requestParamsSchema.extend({
    mode: z.literal("url"),
    message: z.string(),
    elicitationId: z.string(),
    url: z.string()
});

export const emptyResultSchema = resultSchema;

export const cancelledNotificationParamsSchema = notificationParamsSchema.extend({
    requestId: requestIdSchema,
    reason: z.string().optional()
});

export const cancelledNotificationSchema = jsonrpcNotificationSchema.extend({
    method: z.literal("notifications/cancelled"),
    params: cancelledNotificationParamsSchema
});

export const clientCapabilitiesSchema = z.object({
    experimental: z.record(z.string(), z.record(z.string(), z.any())).optional(),
    roots: z.object({
        listChanged: z.boolean().optional()
    }).optional(),
    sampling: z.object({
        context: z.record(z.string(), z.any()).optional(),
        tools: z.record(z.string(), z.any()).optional()
    }).optional(),
    elicitation: z.object({
        form: z.record(z.string(), z.any()).optional(),
        url: z.record(z.string(), z.any()).optional()
    }).optional()
});

export const serverCapabilitiesSchema = z.object({
    experimental: z.record(z.string(), z.record(z.string(), z.any())).optional(),
    logging: z.record(z.string(), z.any()).optional(),
    completions: z.record(z.string(), z.any()).optional(),
    prompts: z.object({
        listChanged: z.boolean().optional()
    }).optional(),
    resources: z.object({
        subscribe: z.boolean().optional(),
        listChanged: z.boolean().optional()
    }).optional(),
    tools: z.object({
        listChanged: z.boolean().optional()
    }).optional()
});

export const initializedNotificationSchema = jsonrpcNotificationSchema.extend({
    method: z.literal("notifications/initialized"),
    params: notificationParamsSchema.optional()
});

export const iconSchema = z.object({
    src: z.string(),
    mimeType: z.string().optional(),
    sizes: z.array(z.string()).optional(),
    theme: z.union([z.literal("light"), z.literal("dark")]).optional()
});

export const iconsSchema = z.object({
    icons: z.array(iconSchema).optional()
});

export const baseMetadataSchema = z.object({
    name: z.string(),
    title: z.string().optional()
});

export const implementationSchema = baseMetadataSchema.extend(iconsSchema.shape).extend({
    version: z.string(),
    description: z.string().optional(),
    websiteUrl: z.string().optional()
});

export const pingRequestSchema = jsonrpcRequestSchema.extend({
    method: z.literal("ping"),
    params: requestParamsSchema.optional()
});

export const progressNotificationParamsSchema = notificationParamsSchema.extend({
    progressToken: progressTokenSchema,
    progress: z.number(),
    total: z.number().optional(),
    message: z.string().optional()
});

export const progressNotificationSchema = jsonrpcNotificationSchema.extend({
    method: z.literal("notifications/progress"),
    params: progressNotificationParamsSchema
});

export const paginatedRequestParamsSchema = requestParamsSchema.extend({
    cursor: cursorSchema.optional()
});

export const paginatedRequestSchema = jsonrpcRequestSchema.extend({
    params: paginatedRequestParamsSchema.optional()
});

export const paginatedResultSchema = resultSchema.extend({
    nextCursor: cursorSchema.optional()
});

export const listResourcesRequestSchema = paginatedRequestSchema.extend({
    method: z.literal("resources/list")
});

export const listResourceTemplatesRequestSchema = paginatedRequestSchema.extend({
    method: z.literal("resources/templates/list")
});

export const resourceRequestParamsSchema = requestParamsSchema.extend({
    uri: z.string()
});

export const readResourceRequestParamsSchema = resourceRequestParamsSchema;

export const readResourceRequestSchema = jsonrpcRequestSchema.extend({
    method: z.literal("resources/read"),
    params: readResourceRequestParamsSchema
});

export const resourceListChangedNotificationSchema = jsonrpcNotificationSchema.extend({
    method: z.literal("notifications/resources/list_changed"),
    params: notificationParamsSchema.optional()
});

export const subscribeRequestParamsSchema = resourceRequestParamsSchema;

export const subscribeRequestSchema = jsonrpcRequestSchema.extend({
    method: z.literal("resources/subscribe"),
    params: subscribeRequestParamsSchema
});

export const unsubscribeRequestParamsSchema = resourceRequestParamsSchema;

export const unsubscribeRequestSchema = jsonrpcRequestSchema.extend({
    method: z.literal("resources/unsubscribe"),
    params: unsubscribeRequestParamsSchema
});

export const resourceUpdatedNotificationParamsSchema = notificationParamsSchema.extend({
    uri: z.string()
});

export const resourceUpdatedNotificationSchema = jsonrpcNotificationSchema.extend({
    method: z.literal("notifications/resources/updated"),
    params: resourceUpdatedNotificationParamsSchema
});

export const resourceContentsSchema = z.object({
    uri: z.string(),
    mimeType: z.string().optional(),
    _meta: z.record(z.string(), z.unknown()).optional()
});

export const textResourceContentsSchema = resourceContentsSchema.extend({
    text: z.string()
});

export const blobResourceContentsSchema = resourceContentsSchema.extend({
    blob: z.string()
});

export const listPromptsRequestSchema = paginatedRequestSchema.extend({
    method: z.literal("prompts/list")
});

export const getPromptRequestParamsSchema = requestParamsSchema.extend({
    name: z.string(),
    arguments: z.record(z.string(), z.string()).optional()
});

export const getPromptRequestSchema = jsonrpcRequestSchema.extend({
    method: z.literal("prompts/get"),
    params: getPromptRequestParamsSchema
});

export const promptArgumentSchema = baseMetadataSchema.extend({
    description: z.string().optional(),
    required: z.boolean().optional()
});

export const roleSchema = z.union([z.literal("user"), z.literal("assistant")]);

export const annotationsSchema = z.object({
    audience: z.array(roleSchema).optional(),
    priority: z.number().min(0).max(1).optional(),
    lastModified: z.string().optional()
});

export const promptListChangedNotificationSchema = jsonrpcNotificationSchema.extend({
    method: z.literal("notifications/prompts/list_changed"),
    params: notificationParamsSchema.optional()
});

export const listToolsRequestSchema = paginatedRequestSchema.extend({
    method: z.literal("tools/list")
});

export const callToolRequestParamsSchema = requestParamsSchema.extend({
    name: z.string(),
    arguments: z.record(z.string(), z.unknown()).optional()
});

export const callToolRequestSchema = jsonrpcRequestSchema.extend({
    method: z.literal("tools/call"),
    params: callToolRequestParamsSchema
});

export const toolListChangedNotificationSchema = jsonrpcNotificationSchema.extend({
    method: z.literal("notifications/tools/list_changed"),
    params: notificationParamsSchema.optional()
});

export const toolAnnotationsSchema = z.object({
    title: z.string().optional(),
    readOnlyHint: z.boolean().optional(),
    destructiveHint: z.boolean().optional(),
    idempotentHint: z.boolean().optional(),
    openWorldHint: z.boolean().optional()
});

export const toolSchema = baseMetadataSchema.extend(iconsSchema.shape).extend({
    description: z.string().optional(),
    inputSchema: z.object({
        type: z.literal("object"),
        properties: z.record(z.string(), z.record(z.string(), z.any())).optional(),
        required: z.array(z.string()).optional()
    }),
    outputSchema: z.object({
        type: z.literal("object"),
        properties: z.record(z.string(), z.record(z.string(), z.any())).optional(),
        required: z.array(z.string()).optional()
    }).optional(),
    annotations: toolAnnotationsSchema.optional(),
    _meta: z.record(z.string(), z.unknown()).optional()
});

export const loggingLevelSchema = z.union([z.literal("debug"), z.literal("info"), z.literal("notice"), z.literal("warning"), z.literal("error"), z.literal("critical"), z.literal("alert"), z.literal("emergency")]);

export const setLevelRequestParamsSchema = requestParamsSchema.extend({
    level: loggingLevelSchema
});

export const loggingMessageNotificationParamsSchema = notificationParamsSchema.extend({
    level: loggingLevelSchema,
    logger: z.string().optional(),
    data: z.unknown()
});

export const loggingMessageNotificationSchema = jsonrpcNotificationSchema.extend({
    method: z.literal("notifications/message"),
    params: loggingMessageNotificationParamsSchema
});

export const toolChoiceSchema = z.object({
    mode: z.union([z.literal("auto"), z.literal("required"), z.literal("none")]).optional()
});

export const textContentSchema = z.object({
    type: z.literal("text"),
    text: z.string(),
    annotations: annotationsSchema.optional(),
    _meta: z.record(z.string(), z.unknown()).optional()
});

export const imageContentSchema = z.object({
    type: z.literal("image"),
    data: z.string(),
    mimeType: z.string(),
    annotations: annotationsSchema.optional(),
    _meta: z.record(z.string(), z.unknown()).optional()
});

export const audioContentSchema = z.object({
    type: z.literal("audio"),
    data: z.string(),
    mimeType: z.string(),
    annotations: annotationsSchema.optional(),
    _meta: z.record(z.string(), z.unknown()).optional()
});

export const toolUseContentSchema = z.object({
    type: z.literal("tool_use"),
    id: z.string(),
    name: z.string(),
    input: z.record(z.string(), z.unknown()),
    _meta: z.record(z.string(), z.unknown()).optional()
});

export const embeddedResourceSchema = z.object({
    type: z.literal("resource"),
    resource: z.union([textResourceContentsSchema, blobResourceContentsSchema]),
    annotations: annotationsSchema.optional(),
    _meta: z.record(z.string(), z.unknown()).optional()
});

export const modelHintSchema = z.object({
    name: z.string().optional()
});

export const promptReferenceSchema = baseMetadataSchema.extend({
    type: z.literal("ref/prompt")
});

export const resourceTemplateReferenceSchema = z.object({
    type: z.literal("ref/resource"),
    uri: z.string()
});

export const completeRequestParamsSchema = requestParamsSchema.extend({
    ref: z.union([promptReferenceSchema, resourceTemplateReferenceSchema]),
    argument: z.object({
        name: z.string(),
        value: z.string()
    }),
    context: z.object({
        arguments: z.record(z.string(), z.string()).optional()
    }).optional()
});

export const completeResultSchema = resultSchema.extend({
    completion: z.object({
        values: z.array(z.string()),
        total: z.number().optional(),
        hasMore: z.boolean().optional()
    })
});

export const listRootsRequestSchema = jsonrpcRequestSchema.extend({
    method: z.literal("roots/list"),
    params: requestParamsSchema.optional()
});

export const rootSchema = z.object({
    uri: z.string(),
    name: z.string().optional(),
    _meta: z.record(z.string(), z.unknown()).optional()
});

export const rootsListChangedNotificationSchema = jsonrpcNotificationSchema.extend({
    method: z.literal("notifications/roots/list_changed"),
    params: notificationParamsSchema.optional()
});

export const stringSchemaSchema = z.object({
    type: z.literal("string"),
    title: z.string().optional(),
    description: z.string().optional(),
    minLength: z.number().optional(),
    maxLength: z.number().optional(),
    format: z.union([z.literal("email"), z.literal("uri"), z.literal("date"), z.literal("date-time")]).optional(),
    default: z.string().optional()
});

export const numberSchemaSchema = z.object({
    type: z.union([z.literal("number"), z.literal("integer")]),
    title: z.string().optional(),
    description: z.string().optional(),
    minimum: z.number().optional(),
    maximum: z.number().optional(),
    default: z.number().optional()
});

export const booleanSchemaSchema = z.object({
    type: z.literal("boolean"),
    title: z.string().optional(),
    description: z.string().optional(),
    default: z.boolean().optional()
});

export const untitledSingleSelectEnumSchemaSchema = z.object({
    type: z.literal("string"),
    title: z.string().optional(),
    description: z.string().optional(),
    enum: z.array(z.string()),
    default: z.string().optional()
});

export const titledSingleSelectEnumSchemaSchema = z.object({
    type: z.literal("string"),
    title: z.string().optional(),
    description: z.string().optional(),
    oneOf: z.array(z.object({
        const: z.string(),
        title: z.string()
    })),
    default: z.string().optional()
});

export const singleSelectEnumSchemaSchema = z.union([untitledSingleSelectEnumSchemaSchema, titledSingleSelectEnumSchemaSchema]);

export const untitledMultiSelectEnumSchemaSchema = z.object({
    type: z.literal("array"),
    title: z.string().optional(),
    description: z.string().optional(),
    minItems: z.number().optional(),
    maxItems: z.number().optional(),
    items: z.object({
        type: z.literal("string"),
        enum: z.array(z.string())
    }),
    default: z.array(z.string()).optional()
});

export const titledMultiSelectEnumSchemaSchema = z.object({
    type: z.literal("array"),
    title: z.string().optional(),
    description: z.string().optional(),
    minItems: z.number().optional(),
    maxItems: z.number().optional(),
    items: z.object({
        anyOf: z.array(z.object({
            const: z.string(),
            title: z.string()
        }))
    }),
    default: z.array(z.string()).optional()
});

export const multiSelectEnumSchemaSchema = z.union([untitledMultiSelectEnumSchemaSchema, titledMultiSelectEnumSchemaSchema]);

export const legacyTitledEnumSchemaSchema = z.object({
    type: z.literal("string"),
    title: z.string().optional(),
    description: z.string().optional(),
    enum: z.array(z.string()),
    enumNames: z.array(z.string()).optional(),
    default: z.string().optional()
});

export const enumSchemaSchema = z.union([singleSelectEnumSchemaSchema, multiSelectEnumSchemaSchema, legacyTitledEnumSchemaSchema]);

export const elicitResultSchema = resultSchema.extend({
    action: z.union([z.literal("accept"), z.literal("decline"), z.literal("cancel")]),
    content: z.record(z.string(), z.union([z.string(), z.number(), z.boolean(), z.array(z.string())])).optional()
});

export const elicitationCompleteNotificationSchema = jsonrpcNotificationSchema.extend({
    method: z.literal("notifications/elicitation/complete"),
    params: z.object({
        elicitationId: z.string()
    })
});

export const completeRequestSchema = jsonrpcRequestSchema.extend({
    method: z.literal("completion/complete"),
    params: completeRequestParamsSchema
});

export const setLevelRequestSchema = jsonrpcRequestSchema.extend({
    method: z.literal("logging/setLevel"),
    params: setLevelRequestParamsSchema
});

export const clientNotificationSchema = z.union([cancelledNotificationSchema, progressNotificationSchema, initializedNotificationSchema, rootsListChangedNotificationSchema]);

export const listRootsResultSchema = resultSchema.extend({
    roots: z.array(rootSchema)
});

export const serverNotificationSchema = z.union([cancelledNotificationSchema, progressNotificationSchema, loggingMessageNotificationSchema, resourceUpdatedNotificationSchema, resourceListChangedNotificationSchema, toolListChangedNotificationSchema, promptListChangedNotificationSchema, elicitationCompleteNotificationSchema]);

export const initializeResultSchema = resultSchema.extend({
    protocolVersion: z.string(),
    capabilities: serverCapabilitiesSchema,
    serverInfo: implementationSchema,
    instructions: z.string().optional()
});

export const readResourceResultSchema = resultSchema.extend({
    contents: z.array(z.union([textResourceContentsSchema, blobResourceContentsSchema]))
});

export const listToolsResultSchema = paginatedResultSchema.extend({
    tools: z.array(toolSchema)
});

export const jsonrpcMessageSchema = z.union([jsonrpcRequestSchema, jsonrpcNotificationSchema, jsonrpcResponseSchema, jsonrpcErrorSchema]);

export const urlElicitationRequiredErrorSchema = jsonrpcErrorSchema.omit({ "error": true }).extend({
    error: errorSchema.and(z.object({
        code: z.any(),
        data: z.record(z.string(), z.unknown()).and(z.object({
            elicitations: z.array(elicitRequestUrlParamsSchema)
        }))
    }))
});

export const initializeRequestParamsSchema = requestParamsSchema.extend({
    protocolVersion: z.string(),
    capabilities: clientCapabilitiesSchema,
    clientInfo: implementationSchema
});

export const initializeRequestSchema = jsonrpcRequestSchema.extend({
    method: z.literal("initialize"),
    params: initializeRequestParamsSchema
});

export const resourceSchema = baseMetadataSchema.extend(iconsSchema.shape).extend({
    uri: z.string(),
    description: z.string().optional(),
    mimeType: z.string().optional(),
    annotations: annotationsSchema.optional(),
    size: z.number().optional(),
    _meta: z.record(z.string(), z.unknown()).optional()
});

export const resourceTemplateSchema = baseMetadataSchema.extend(iconsSchema.shape).extend({
    uriTemplate: z.string(),
    description: z.string().optional(),
    mimeType: z.string().optional(),
    annotations: annotationsSchema.optional(),
    _meta: z.record(z.string(), z.unknown()).optional()
});

export const promptSchema = baseMetadataSchema.extend(iconsSchema.shape).extend({
    description: z.string().optional(),
    arguments: z.array(promptArgumentSchema).optional(),
    _meta: z.record(z.string(), z.unknown()).optional()
});

export const resourceLinkSchema = resourceSchema.extend({
    type: z.literal("resource_link")
});

export const contentBlockSchema = z.union([textContentSchema, imageContentSchema, audioContentSchema, resourceLinkSchema, embeddedResourceSchema]);

export const modelPreferencesSchema = z.object({
    hints: z.array(modelHintSchema).optional(),
    costPriority: z.number().min(0).max(1).optional(),
    speedPriority: z.number().min(0).max(1).optional(),
    intelligencePriority: z.number().min(0).max(1).optional()
});

export const toolResultContentSchema = z.object({
    type: z.literal("tool_result"),
    toolUseId: z.string(),
    content: z.array(contentBlockSchema),
    structuredContent: z.record(z.string(), z.unknown()).optional(),
    isError: z.boolean().optional(),
    _meta: z.record(z.string(), z.unknown()).optional()
});

export const primitiveSchemaDefinitionSchema = z.union([stringSchemaSchema, numberSchemaSchema, booleanSchemaSchema, enumSchemaSchema]);

export const elicitRequestFormParamsSchema = requestParamsSchema.extend({
    mode: z.literal("form").optional(),
    message: z.string(),
    requestedSchema: z.object({
        $schema: z.string().optional(),
        type: z.literal("object"),
        properties: z.record(z.string(), primitiveSchemaDefinitionSchema),
        required: z.array(z.string()).optional()
    })
});

export const elicitRequestParamsSchema = z.union([elicitRequestFormParamsSchema, elicitRequestUrlParamsSchema]);

export const clientRequestSchema = z.union([pingRequestSchema, initializeRequestSchema, completeRequestSchema, setLevelRequestSchema, getPromptRequestSchema, listPromptsRequestSchema, listResourcesRequestSchema, listResourceTemplatesRequestSchema, readResourceRequestSchema, subscribeRequestSchema, unsubscribeRequestSchema, callToolRequestSchema, listToolsRequestSchema]);

export const elicitRequestSchema = jsonrpcRequestSchema.extend({
    method: z.literal("elicitation/create"),
    params: elicitRequestParamsSchema
});

export const listPromptsResultSchema = paginatedResultSchema.extend({
    prompts: z.array(promptSchema)
});

export const listResourceTemplatesResultSchema = paginatedResultSchema.extend({
    resourceTemplates: z.array(resourceTemplateSchema)
});

export const listResourcesResultSchema = paginatedResultSchema.extend({
    resources: z.array(resourceSchema)
});

export const callToolResultSchema = resultSchema.extend({
    content: z.array(contentBlockSchema),
    structuredContent: z.record(z.string(), z.unknown()).optional(),
    isError: z.boolean().optional()
});

export const promptMessageSchema = z.object({
    role: roleSchema,
    content: contentBlockSchema
});

export const samplingMessageContentBlockSchema = z.union([textContentSchema, imageContentSchema, audioContentSchema, toolUseContentSchema, toolResultContentSchema]);

export const getPromptResultSchema = resultSchema.extend({
    description: z.string().optional(),
    messages: z.array(promptMessageSchema)
});

export const samplingMessageSchema = z.object({
    role: roleSchema,
    content: z.union([samplingMessageContentBlockSchema, z.array(samplingMessageContentBlockSchema)]),
    _meta: z.record(z.string(), z.unknown()).optional()
});

export const createMessageRequestParamsSchema = requestParamsSchema.extend({
    messages: z.array(samplingMessageSchema),
    modelPreferences: modelPreferencesSchema.optional(),
    systemPrompt: z.string().optional(),
    includeContext: z.union([z.literal("none"), z.literal("thisServer"), z.literal("allServers")]).optional(),
    temperature: z.number().optional(),
    maxTokens: z.number(),
    stopSequences: z.array(z.string()).optional(),
    metadata: z.record(z.string(), z.any()).optional(),
    tools: z.array(toolSchema).optional(),
    toolChoice: toolChoiceSchema.optional()
});

export const createMessageResultSchema = resultSchema.extend(samplingMessageSchema.shape).extend({
    model: z.string(),
    stopReason: z.union([z.literal("endTurn"), z.literal("stopSequence"), z.literal("maxTokens"), z.literal("toolUse"), z.string()]).optional()
});

export const clientResultSchema = z.union([emptyResultSchema, createMessageResultSchema, listRootsResultSchema, elicitResultSchema]);

export const createMessageRequestSchema = jsonrpcRequestSchema.extend({
    method: z.literal("sampling/createMessage"),
    params: createMessageRequestParamsSchema
});

export const serverResultSchema = z.union([emptyResultSchema, initializeResultSchema, completeResultSchema, getPromptResultSchema, listPromptsResultSchema, listResourceTemplatesResultSchema, listResourcesResultSchema, readResourceResultSchema, callToolResultSchema, listToolsResultSchema]);

export const serverRequestSchema = z.union([pingRequestSchema, createMessageRequestSchema, listRootsRequestSchema, elicitRequestSchema]);
