import { describe, it, expect } from 'vitest';
import { createPrivateKeyJwtAuth } from './auth-extensions.js';

describe('createPrivateKeyJwtAuth', () => {
    const baseOptions = {
        issuer: 'client-id',
        subject: 'client-id',
        privateKey: 'a-string-secret-at-least-256-bits-long',
        alg: 'HS256'
    };

    it('creates an addClientAuthentication function that sets JWT assertion params', async () => {
        const addClientAuth = createPrivateKeyJwtAuth(baseOptions);

        const headers = new Headers();
        const params = new URLSearchParams();

        await addClientAuth(headers, params, 'https://auth.example.com/token', undefined);

        expect(params.get('client_assertion')).toBeTruthy();
        expect(params.get('client_assertion_type')).toBe('urn:ietf:params:oauth:client-assertion-type:jwt-bearer');

        // Verify JWT structure (three dot-separated segments)
        const assertion = params.get('client_assertion')!;
        const parts = assertion.split('.');
        expect(parts).toHaveLength(3);
    });

    it('creates a signed JWT when using a Uint8Array HMAC key', async () => {
        const secret = new TextEncoder().encode('a-string-secret-at-least-256-bits-long');

        const addClientAuth = createPrivateKeyJwtAuth({
            issuer: 'client-id',
            subject: 'client-id',
            privateKey: secret,
            alg: 'HS256'
        });

        const params = new URLSearchParams();
        await addClientAuth(new Headers(), params, 'https://auth.example.com/token', undefined);

        const assertion = params.get('client_assertion')!;
        const parts = assertion.split('.');
        expect(parts).toHaveLength(3);
    });

    it('creates a signed JWT when using a symmetric JWK key', async () => {
        const jwk: Record<string, unknown> = {
            kty: 'oct',
            // "a-string-secret-at-least-256-bits-long" base64url-encoded
            k: 'YS1zdHJpbmctc2VjcmV0LWF0LWxlYXN0LTI1Ni1iaXRzLWxvbmc',
            alg: 'HS256'
        };

        const addClientAuth = createPrivateKeyJwtAuth({
            issuer: 'client-id',
            subject: 'client-id',
            privateKey: jwk,
            alg: 'HS256'
        });

        const params = new URLSearchParams();
        await addClientAuth(new Headers(), params, 'https://auth.example.com/token', undefined);

        const assertion = params.get('client_assertion')!;
        const parts = assertion.split('.');
        expect(parts).toHaveLength(3);
    });

    it('creates a signed JWT when using an RSA PEM private key', async () => {
        /**
         * Generated by the following command:
         * 1) Generate an RSA private key (PKCS#1 format)
         * ```bash
         * openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -out rsa-key.pem
         * ```
         * 2) Convert it to PKCS#8 (what `jose.importPKCS8` expects)
         * ```bash
         * openssl pkcs8 -topk8 -nocrypt -in rsa-key.pem -out rsa-key-pkcs8.pem
         * ```
         */
        const pem = `-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCruEwXtZ4MXsYl
ONRMtvBnOZNtnYWlO1KJs93gROCxzRzHz8I5dSzNBYgk5fwncd4L/ZJn3Ue8DsZL
0KzF1W9wweq/EsVYwhTxkLsfkaVVJld4DuYlAATCMiQYN7f4LfdmXaz1o+2kB5Ug
Ae9DqcrSXWcO7gbt1ABJdomPuwFurD9bZKANB/zM+MsAohXGVDoN8o7QH6hWFT/4
7x3ANoH2oT2mvF58F9Fh6DkGcE9BG3+Ze3TOoCx2DhqdjK8/artxIKigiVXUxLwx
4FB/cSmdh3KpldC1UkmPpyzwMGKe4BlsghXxssyuNBMEi3J1+peiMzN0c4YU5B6A
9jFLMsQXAgMBAAECggEAOxnnNpHPn7pOwCjbCLw96YkrcKKyiLfuJG6/gpyyKP/L
VAnxcw0dKkMpJGnzazAJmF7hsNW8BsGfBiEAFebrwAc94B15xp6lzq5dePQLz06u
9CdMlpd3C89uFNe4fbZ0W8sJ6FFPTRE/BhEkZElgAR8chUrvH5PDtYUSu2FFkO0u
8/RFEPj0urL93kzwaWzff91px82Tn4sak5rK6NfeeoLabyUAoc+E+vDvB8RZW3/1
sdQ/zp09XZqsw45WS8oHJmDlV/eB2tICha/bC/FygkZY+SmkX4L9a6rz2f+mjlHc
afSYMBLa93/Q4HUzeZcP5HOKr7vM/uC06aYqwXfJAQKBgQDiKBh8LJPeLkrzML7J
160vY/T5b92qt4B8odR6jgySDg/4YbW5Ie6Lydim9G+yu4xodRpJZ0tm9r02Sieq
gvYSzPrdbuiU7jnwCBmeDsoaSsxy+zKNE5TBRBDbwmuaQHlkdDKp9Bd90itp8qMm
YGBu1Rqn7A/xCWkmZA16TaGwtwKBgQDCYT/Hv/iSbzIgbzQTESP3f2WSaUye0MKu
kASLo3IsWgwyrdtLEZ0BYMoibasRj0351wtk2FxOy1t8+Wz80BBi57MTaZgbcYHi
XcaB0imBl+hQinK6PnY/LJN2ZPp7fMSPJ8kE4kmxcAAH0A56UDpOn5Fnle9PMS/W
cjj5Xd9noQKBgEM9QpJgupH7V4NYgdEHE9GcOXCUBubD6iqj/sV1SF2AWtUxT9M8
OG1NVOHGmRMd2dAQyQD7+hohz/29LG/wwfKzCP8fA32MGqO39M3efc41YPXqo4v4
P2j6sLx14IIbGzx3o7yN+xIIk6nLXyCA1Qr+xw8YC2FRt/aXFr6/KAyfAoGAThZz
YPOmEG3LXWxPJznDkTIExAS5WzPSgf4pVU+cFmU2cUWWy1mQEXWovpwAFVXUpYHW
efTRYHYhkttBBW8wpgsezbWl/aBj5WR20sBzHDTCh1iXLmrZZheqRe3bErDU5g29
m9CsejPcT0cuCcUhJ2TDLTH2qYHBDg1lBgjILwECgYB7J5HgEl2pgg+RxuiQd11x
ERSttiQtJ91cm+rOS0DAoviTDd1lvvrKlSxw9eMKO1UX/nLkFeEAnxxc7RPlsMb/
wZs2jVskGA6OxU/II0nCh9C+hp1LV4vl5Hy1mM3Lkqa/I/AC4kJdvTwi45lXpM9o
btHHccicX+r3BsSv5adOxQ==
-----END PRIVATE KEY-----`;

        const addClientAuth = createPrivateKeyJwtAuth({
            issuer: 'client-id',
            subject: 'client-id',
            privateKey: pem,
            alg: 'RS256'
        });

        const params = new URLSearchParams();
        await addClientAuth(new Headers(), params, 'https://auth.example.com/token', undefined);

        const assertion = params.get('client_assertion')!;
        const parts = assertion.split('.');
        expect(parts).toHaveLength(3);
    });

    it('uses metadata.issuer as audience when available', async () => {
        const addClientAuth = createPrivateKeyJwtAuth(baseOptions);

        const params = new URLSearchParams();
        await addClientAuth(new Headers(), params, 'https://auth.example.com/token', {
            issuer: 'https://issuer.example.com',
            authorization_endpoint: 'https://auth.example.com/authorize',
            token_endpoint: 'https://auth.example.com/token',
            response_types_supported: ['code']
        });

        const assertion = params.get('client_assertion')!;
        // Decode the payload to verify audience
        const [, payloadB64] = assertion.split('.');
        const payload = JSON.parse(Buffer.from(payloadB64, 'base64url').toString());
        expect(payload.aud).toBe('https://issuer.example.com');
    });

    it('throws when using an unsupported algorithm', async () => {
        const addClientAuth = createPrivateKeyJwtAuth({
            issuer: 'client-id',
            subject: 'client-id',
            privateKey: 'a-string-secret-at-least-256-bits-long',
            alg: 'none'
        });

        const params = new URLSearchParams();
        await expect(
            addClientAuth(new Headers(), params, 'https://auth.example.com/token', undefined)
        ).rejects.toThrow('Unsupported algorithm none');
    });

    it('throws when jose cannot import an invalid RSA PEM key', async () => {
        const badPem = '-----BEGIN PRIVATE KEY-----\nnot-a-valid-key\n-----END PRIVATE KEY-----';

        const addClientAuth = createPrivateKeyJwtAuth({
            issuer: 'client-id',
            subject: 'client-id',
            privateKey: badPem,
            alg: 'RS256'
        });

        const params = new URLSearchParams();
        await expect(
            addClientAuth(new Headers(), params, 'https://auth.example.com/token', undefined)
        ).rejects.toThrow(/Invalid character/);
    });

    it('throws when jose cannot import a mismatched JWK key', async () => {
        const jwk: Record<string, unknown> = {
            kty: 'oct',
            k: 'c2VjcmV0LWtleQ', // "secret-key" base64url
            alg: 'HS256'
        };

        const addClientAuth = createPrivateKeyJwtAuth({
            issuer: 'client-id',
            subject: 'client-id',
            privateKey: jwk,
            // Ask for an RSA algorithm with an octet key, which should cause jose.importJWK to fail
            alg: 'RS256'
        });

        const params = new URLSearchParams();
        await expect(
            addClientAuth(new Headers(), params, 'https://auth.example.com/token', undefined)
        ).rejects.toThrow(/Key for the RS256 algorithm must be one of type CryptoKey, KeyObject, or JSON Web Key/);
    });
});
